<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<title>wxWidgets: C++ Exceptions</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<link href="extra_stylesheet.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="page_container">
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0" style="width: 100%;">
 <tbody>
 <tr>
  <td id="projectlogo">
    <a href="https://www.wxwidgets.org/" target="_new">
      <img alt="wxWidgets" src="logo.png"/>
    </a>
  </td>
  <td style="padding-left: 0.5em; text-align: right;">
   <span id="projectnumber">Version: 3.1.4</span>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="index.html">Documentation</a></li><li class="navelem"><a class="el" href="page_topics.html">Programming Guides</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">C++ Exceptions </div>  </div>
</div><!--header-->
<div class="contents">
<div class="toc"><h3>Table of Contents</h3>
<ul><li class="level1"><a href="#overview_exceptions_strategies">Strategies for Exception Handling</a></li>
<li class="level1"><a href="#overview_exceptions_store_rethrow">Handling Exception Inside wxYield()</a></li>
<li class="level1"><a href="#overview_exceptions_tech">Technicalities</a></li>
</ul>
</div>
<div class="textblock"><p>wxWidgets had been started long before the exceptions were introduced in C++ so it is not very surprising that it is not built around using them as some more modern C++ libraries are.</p>
<p>For instance, the library doesn't throw exceptions to signal about the errors. Moreover, up to (and including) the version 2.4 of wxWidgets, even using the exceptions in the user code was dangerous because the library code wasn't exception-safe and so an exception propagating through it could result in memory and/or resource leaks, and also not very convenient.</p>
<p>However the recent wxWidgets versions are exception-friendly. This means that while the library still doesn't use the exceptions by itself, it should be now safe to use the exceptions in the user code and the library tries to help you with this.</p>
<h1><a class="anchor" id="overview_exceptions_strategies"></a>
Strategies for Exception Handling</h1>
<p>There are several choice for using the exceptions in wxWidgets programs. First of all, you may not use them at all. As stated above, the library doesn't throw any exceptions by itself and so you don't have to worry about exceptions at all unless your own code throws them. This is, of course, the simplest solution but may be not the best one to deal with all possible errors.</p>
<p>The next simplest strategy is to only use exceptions inside non-GUI code, i.e. never let unhandled exceptions escape the event handler in which it happened. In this case using exceptions in wxWidgets programs is not different from using them in any other C++ program.</p>
<p>Things get more interesting if you decide to let (at least some) exceptions escape from the event handler in which they occurred. Such exceptions will be caught by wxWidgets and the special <a class="el" href="classwx_app_console.html#aca806b41cf74fd6166e4fb2e2708e9bf" title="This function is called if an unhandled exception occurs inside the main application event loop...">wxApp::OnExceptionInMainLoop()</a> method will be called from the <code>catch</code> clause. This allows you to decide in a single place what to do about such exceptions: you may want to handle the exception somehow or terminate the program. In this sense, OnExceptionInMainLoop() is equivalent to putting a <code>try/catch</code> block around the entire <code>main()</code> function body in the traditional console programs. However notice that, as its name indicates, this method won't help you with the exceptions thrown before the main loop is started or after it is over, so you may still want to have <code>try/catch</code> in your overridden <a class="el" href="classwx_app_console.html#a99953775a2fd83fa2456e390779afe15" title="This must be provided by the application, and will usually create the application&#39;s main window...">wxApp::OnInit()</a> and <a class="el" href="classwx_app_console.html#a5ee60051c92b0b2933258799626a0485" title="Override this member function for any processing which needs to be done as the application is about t...">wxApp::OnExit()</a> methods too, otherwise <a class="el" href="classwx_app_console.html#a8c241ae1aa045da4470664813b7ec960" title="This function is called when an unhandled C++ exception occurs in user code called by wxWidgets...">wxApp::OnUnhandledException()</a> will be called.</p>
<p>Finally, notice that even if you decide to not let any exceptions escape in this way, this still may happen unexpectedly in a program using exceptions as a result of a bug. So consider always overriding OnExceptionInMainLoop() in your wxApp-derived class if you use exceptions in your program, whether you expect it to be called or not. In the latter case you may simple re-throw the exception and let it bubble up to OnUnhandledException() as well.</p>
<p>To summarize, when you use exceptions in your code, you may handle them in the following places, in order of priority:</p><ol type="1">
<li>In a <code>try/catch</code> block inside an event handler.</li>
<li>In <a class="el" href="classwx_app_console.html#aca806b41cf74fd6166e4fb2e2708e9bf" title="This function is called if an unhandled exception occurs inside the main application event loop...">wxApp::OnExceptionInMainLoop()</a>.</li>
<li>In <a class="el" href="classwx_app_console.html#a8c241ae1aa045da4470664813b7ec960" title="This function is called when an unhandled C++ exception occurs in user code called by wxWidgets...">wxApp::OnUnhandledException()</a>.</li>
</ol>
<p>In the first two cases you may decide whether you want to handle the exception and continue execution or to exit the program. In the last one the program is about to exit already so you can just try to save any unsaved data and notify the user about the problem (while being careful not to throw any more exceptions as otherwise <code>std::terminate()</code> will be called).</p>
<h1><a class="anchor" id="overview_exceptions_store_rethrow"></a>
Handling Exception Inside wxYield()</h1>
<p>In some, relatively rare cases, using <a class="el" href="classwx_app_console.html#aca806b41cf74fd6166e4fb2e2708e9bf" title="This function is called if an unhandled exception occurs inside the main application event loop...">wxApp::OnExceptionInMainLoop()</a> may not be sufficiently flexible. The most common example is using automated GUI tests, when test failures are signaled by throwing an exception and these exceptions can't be caught in a single central method because their handling depends on the test logic, e.g. sometimes an exception is expected while at other times it is an actual error. Typically this results in writing code like the following:</p>
<div class="fragment"><div class="line"><span class="keywordtype">void</span> TestNewDocument()</div><div class="line">{</div><div class="line">    <a class="code" href="classwx_u_i_action_simulator.html">wxUIActionSimulator</a> ui;</div><div class="line">    ui.<a class="code" href="classwx_u_i_action_simulator.html#a573e464dc75d6168564a6372f6b9aa21">Char</a>(<span class="charliteral">&#39;n&#39;</span>, <a class="code" href="defs_8h.html#a5b81968ab866f5874cabc504490ae5cda08db85848fe8fa43b85ba115050384db">wxMOD_CONTROL</a>); <span class="comment">// simulate creating a new file</span></div><div class="line"></div><div class="line">    <span class="comment">// Let wxWidgets dispatch Ctrl+N event, invoke the handler and create the</span></div><div class="line">    <span class="comment">// new document.</span></div><div class="line">    <span class="keywordflow">try</span> {</div><div class="line">        <a class="code" href="group__group__funcmacro__appinitterm.html#gac386c89a04e364afc07edce6d848c27a">wxYield</a>();</div><div class="line">    } <span class="keywordflow">catch</span> ( ... ) {</div><div class="line">        <span class="comment">// Handle exceptions as failure in the new document creation test.</span></div><div class="line">    }</div><div class="line">}</div></div><!-- fragment --><p>Unfortunately, by default this example only works when using a C++11 compiler because the exception can't be safely propagated back to the code handling it in <code>TestNewDocument()</code> through the system event dispatch functions which are not compatible with C++ exceptions and needs to be stored by wxWidgets when it is first caught and rethrown later, when it is safe to do it. And such storing and rethrowing of exceptions is only possible in C++11, so while everything just works if you do use C++11, there is an extra step if you are using C++98: In this case you need to override <a class="el" href="classwx_app_console.html#ac96643e4a1b1320cdd75e4a7eac22abc" title="Method to store exceptions not handled by OnExceptionInMainLoop(). ">wxApp::StoreCurrentException()</a> and <a class="el" href="classwx_app_console.html#a2b04fb3d24e16cd4bcf7ca208ef0ef4c" title="Method to rethrow exceptions stored by StoreCurrentException(). ">wxApp::RethrowStoredException()</a> to help wxWidgets to do this, please see the documentation of these functions for more details.</p>
<h1><a class="anchor" id="overview_exceptions_tech"></a>
Technicalities</h1>
<p>To use any kind of exception support in the library you need to build it with <code>wxUSE_EXCEPTIONS</code> set to 1. It is turned on by default but you may wish to check <code>include/wx/msw/setup.h</code> file under Windows or run <code>configure</code> with explicit <code>--enable-exceptions</code> argument under Unix.</p>
<p>On the other hand, if you do not plan to use exceptions, setting this flag to 0 or using <code>--disable-exceptions</code> could result in a leaner and slightly faster library.</p>
<p>As for any other library feature, there is a sample (<code>except</code>) showing how to use it. Please look at its sources for further information. </p>
</div></div><!-- contents -->

<address class="footer">
	<small>
		Generated on Wed Jul 22 2020 19:22:38 for wxWidgets by <a href="http://www.doxygen.org/index.html" target="_new">Doxygen</a> 1.8.13
	</small>
</address>
<script src="wxwidgets.js" type="text/javascript"></script>
</div><!-- #page_container -->
</body>
</html>